import pygame
from pathlib import Path

BASE_DIR = Path(__file__).parent.parent.parent

SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800

GAME_NAME = "Moorhuhn"

BACKGROUND_COLOR = (0, 0, 0)
BUTTON_WIDTH = SCREEN_WIDTH * 0.18
BUTTON_HEIGHT = SCREEN_HEIGHT * 0.0875
BORDER_RADIUS = 10

BASIC_FONT = BASE_DIR / "assets/fonts/main.otf"
BASIC_FONT_SIZE = 20
RULES_FONT_SIZE = 18

BASIC_BACKGROUND_COLOR = (128,0,0)
BASIC_BACKGROUND_HOVER_COLOR=(200,0,0)
BASIC_COLOR = (255,255,255)
RULES_COLOR = (0,0,0)

NAME_PLAY = "Играть"
NAME_TABLE_RECORD = "Таблица рекордов"
NAME_HELP = "Справка"
NAME_QUIT = "Выйти"
NAME_BACK = "Назад"

COORD_Y_FIRST_BUTTON = SCREEN_HEIGHT*0.2375
COORD_Y_START_TEXT = SCREEN_HEIGHT*0.20
COORD_Y_BACK_BUTTON = SCREEN_HEIGHT*0.60
HEIGHT_BETWEEN_BUTTONS = SCREEN_HEIGHT*0.1125

MENU_BACKGROUND_IMAGE = BASE_DIR / "assets/images/result_menu2.png"
HELP_MENU_BACKGROUND_IMAGE = BASE_DIR / "assets/images/help_menu.png"

FILE_RULES_PATH = BASE_DIR / "assets/config/rules.txt"